# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c50e24a506b82048bda47ed3fd0f86d222ae0a375c9b7442f3cd2c903e7c82a4d76eaf402d9a09de879724bb7063fa20d11f38e742f697ff5fc6ce272249276

test:
  secret_key_base: df58daa51490d4757c8ad2ddf913f5cfaf6a842c2e76699b643be2127df84f20d2fca4492d97ef6b7c81fd0046da3fb8704a66e5c9c708240c70316eef4c2805

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
